resilience4j:
  circuitBreaker:
    configs:
      default:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 4
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
    instances:
      products:
        baseConfig: default
  timeLimiter:
    configs:
      default:
        timeoutDuration: 2s
    instances:
      products:
        baseConfig: default

spring:
  cloud:
    gateway:
      routes:
        - id: product-server
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
            - Header=token, \d+
            - Header=Content-Type, application/json
            - Method=GET, POST
            - Query=color, verde
            - Cookie=color, azul
          filters:
            - CircuitBreaker=products
            - StripPrefix=2
            - name: Demo
              args:
                message: Mensaje Demo filtro personalizado =)
                coockieName: user
                coockieValor: JRuiz
        - id: item-service
          uri: lb://item-server
          predicates:
            - Path=/api/item/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, 123456
            - AddResponseHeader=token-response, 12345678
            - SetResponseHeader=Content-Type, text/plain
            - AddRequestParameter=nombre, jruiz